In [1]:
'''1] Write a python program to take list values as input parameters and returns another list without any duplicates.'''
lst=[]
n=int(input("Enter no. of elements\n"))
l=[]
a=[]
for i in range(0,n):
    l=input()
    lst.append(l)
print(lst)
for i in lst:
    if i not in a:
        a.append(i)
print("another list without duplicate is ",a)


Enter no. of elements
5
1
2
3
4
5
['1', '2', '3', '4', '5']
another list without duplicate is  ['1', '2', '3', '4', '5']


In [2]:
'''2] Write a program that takes a string as input from user and computes the frequency of each letters. Use a variable of dictionary type to maintain the count'''
a=input("Enter string\n")
d={}
l=list(a)
for i in l:
    if i not in d:
        d.update({i:a.count(i)})
print("The frequency of each element in the string is ",d)


Enter string
bhavya
The frequency of each element in the string is  {'b': 1, 'h': 1, 'a': 2, 'v': 1, 'y': 1}


In [ ]:
'''3] Write a program to read the numbers until -1 is encountered. Also, count the number of prime numbers and composite numbers entered by the user'''
a=0
count=0
while(a!=-1):
    
        a =int(input("Enter the number "))
        for i in range(0,1):

            if (a==1 or a==0):
                print(a," is niether prime nor composite")
            elif (a==2):
                print("2 is a prime number")
                break
        for i in range(2, a):

            if (a % i == 0):
                print(a," is composite number")
                count=count+1
                print("count of composite number is ",count)
                break
            elif (a%i!=0):
                print(a," is a prime number")
                break


In [ ]:
'''4] Write a program to check whether a number is Armstrong or not.
(Armstrong number is a number that is equal to the sum of cubes of its digits for example: 153 = 1^3 + 5^3 + 3^3.)
'''
num=int(input("Enter number "))
rhs=num
sum=0
while(rhs>0):
    dig=rhs%10
    sum=sum+dig**3
    rhs//=10
    
if num==sum:
    print(+int(num)," is angstrom")
else:
    print(+int(num)," is not angstrom")


In [3]:
'''5] Write a program that accepts a string from user and calculate the number of digits and letters in string.'''
a=input("Enter the string ")
count=0
count1=0
for i in range(0,len(a)):

    if a[i].isdigit():
        count=count+1
        #print("number count= ",count)
        continue
    elif a[i].isalpha():
        count1=count1+1
        #print("count of string is ",count1)
        continue
   # else:
       
       #print("count ",count,count1)
       
print("number count= ",count,"string count ",count1)


Enter the string uyh5285h67y
number count=  6 string count  5


In [ ]:
'''6] WAP to verify whether his credit card numbers are valid or not.  A valid credit card
from ABC Bank has the following characteristics:
●	It must start with a 4,5  or 6 . 
●	It must contain exactly 16 digits. 
●	It must only consist of digits (0-9). 
●	It may have digits in groups of 4, separated by one hyphen ‘-’
'''
import re
credit=input("Enter your credit card number ")
pattern=r'^[4-6]\d{3}[-]\d{4}[-]\d{4}[-]\d{4}$'
pattern1=r'^[4-6]\d{15}$'
if re.search(pattern,credit):
    print("valid entry")
elif re.search(pattern1,credit):
    print("valid entry")
else:
    print("invalid entry")


In [ ]:
'''7] From given string extract phone numbers only and save it into list.
Txt = “Dave Martin
615-555-7164
173 Main St., Springfield RI 55924
davemartin@bogusemail.com

Charles Harris
800-555-5669
969 High St., Atlantis VA 34075
charlesharris@bogusemail.com

Eric Williams
560-555-5153
806 1st St., Faketown AK 86847
laurawilliams@bogusemail.com

Corey Jefferson
900-555-9340
826 Elm St., Epicburg NE 10671
coreyjefferson@bogusemail.com”
'''
import re
pattern=r'\d{3}[-]\d{3}[-]\d{4}'
txt="Dave Martin 615-555-7164 173 Main St., Springfield RI 55924 davemartin@bogusemail.com Charles Harris 800-555-5669 969 High St., Atlantis VA 34075 charlesharris@bogusemail.com Eric Williams 560-555-5153 806 1st St., Faketown AK 86847 laurawilliams@bogusemail.com Corey Jefferson 900-555-9340 826 Elm St., Epicburg NE 10671 coreyjefferson@bogusemail.com"
phone=re.findall(pattern,txt)
print(phone)


In [ ]:
'''8] find all emails'''
import re
pattern=r'\d{3}[-]\d{3}[-]\d{4}'
import re
pattern=r'\d{3}[-]\d{3}[-]\d{4}'
txt="Dave Martin 615-555-7164 173 Main St., Springfield RI 55924 davemartin@bogusemail.com Charles Harris 800-555-5669 969 High St., Atlantis VA 34075 charlesharris@bogusemail.com Eric Williams 560-555-5153 806 1st St., Faketown AK 86847 laurawilliams@bogusemail.com Corey Jefferson 900-555-9340 826 Elm St., Epicburg NE 10671 coreyjefferson@bogusemail.com"
phone=re.findall(pattern,txt)
print(phone)


In [ ]:
'''9] Write a Python program using a recursive function that takes a string as input from the user and displays whether the string is Palindrome or not.'''
def ispal(string):
    if len(string)<=1:
        return True
    else:
        if string[0]==string[-1]:
            return ispal(string[1:-1])
        else:
            return False
string=input("Enter the string ")
palindrome=ispal(string)
if palindrome==True:
    print("It is a pailndrome")
else:
    print("it is not a palindrome")


In [ ]:
'''10] Write a Python program to separate out even and odd numbers from the list entered by user by using Lambda function'''
lst=[]
n=int(input("Enter number of elemnts "))
for i in range(n):
    a=int(input())
    lst.append(a)
print("list is ",lst)
even=list(filter(lambda x: (x%2 ==0),lst))
print("List of even numbers")
print(even)
odd=list(filter(lambda x: (x%2!=0),lst))
print("List of odd numbers")
print(odd)


In [ ]:
'''11] Write a python program to calculate factorial using recursion'''
def factorial(n):
    if n==1 or n==0:
        return n
    else:
        return n*factorial(n-1)
n=int(input("Enter the number "))
if n<0:
    print("impossible factorial")
else:
    print(factorial(n))


In [ ]:
'''12] Write a program to accept Roll Number, Marks Obtained in four subjects, calculate total Marks and percentage scored by the student. Display the roll number, marks obtained, total marks and the percentage scored by the student. Use getter-setter methods.'''
class student:
    marks=[]
    def data(self,name,rn,m1,m2,m3,m4):
        self.name=name
        self.rn=rn
        self.marks.append(m1)
        self.marks.append(m2)
        self.marks.append(m3)
        self.marks.append(m4)
    def display(self):
        print("------------------------")
        print("*****All subjects are of 100 marks****")
        print("Name is ",self.name)
        print("roll no. is ",self.rn)
        print("marks obtained in subject 1 ",self.marks[0])
        print("marks obtained in subject 2 ",self.marks[1])
        print("marks obtained in subject 3 ",self.marks[2])
        print("marks obtained in subject 4 ",self.marks[3])
        print("total marks is ",self.total())
        print("percentage scored is ",self.per(),"%")
        print("------------------------")
    def total(self):
        return(self.marks[0]+self.marks[1]+self.marks[2]+self.marks[3])
    def per(self):
        return([((self.marks[0]+self.marks[1]+self.marks[2]+self.marks[3])/400)*100])
name=input("Enter name= ")
rn=int(input("Enter your roll no.= "))
m1=int(input("Enter marks 1= "))
m2=int(input("Enter marks 2= "))
m3=int(input("Enter marks 3= "))
m4=int(input("Enter marks 4= "))
obj=student()
obj.data(name,rn,m1,m2,m3,m4)
obj.display()


In [ ]:
'''13] 1.	Write a program that has a class ‘store’ which keeps a record of code and price of each product. Display a menu of all products to the user and prompt them to enter the quantity of each item required. Generate a bill and display the total amount.'''
class Store:
    product_list = []
    purchases = {}

    def __init__(self, code, price):
        self.code = code
        self.price = price
        Store.product_list.append(self)

    @classmethod
    def print_menu(cls):
        print("\nMENU:")
        print("Item code", "Price (Rs.)", sep = "\t")
        for item in Store.product_list:
            print(item.code, item.price, sep = "\t\t")
        print()

    @classmethod
    def generate_bill(cls, prod, qty):
        for item in Store.product_list:
            if prod == item.code:
                Store.purchases.update({item.code:qty})
                return item.price * qty
        print("Item not available")
        return 0

    @classmethod
    def print_bill(cls):
        print("\nBILL:")
        print("Item code\tQuantity\tCost")
        for product,quantity in Store.purchases.items():
            print(product, quantity, sep = "\t\t", end = "\t\t")
            print(Store.generate_bill(product, quantity))
        print("Your bill amounts to Rs.", bill_amt)

pen = Store("Pen", 10)
pencil = Store("Pencil", 15)
eraser = Store("Eraser", 5)
ruler = Store("Ruler", 30)
tape = Store("Tape", 50)

Store.print_menu()
cont = 'Y'
bill_amt = 0

while cont.upper() == 'Y':
    prod = input("Enter product code: ")
    qty = int(input("Enter quantity: "))
    bill_amt += Store.generate_bill(prod.capitalize(), qty)
    cont = input("Press y to continue : ")

Store.print_bill()


In [ ]:
'''14] 2.	Assume that a bank maintains two kinds of accounts for customers, one called a savings account and the other as a current account. The savings account provides simple interest and withdrawal facilities but no cheque book facility. The current account provides a check book facility but no interest. Current account holders should also maintain a minimum balance Rs. 500 and if the balance falls below this level, a service charge is imposed to 2%.
 




Create a class account that stores customer name, account number and type of account. From this derive the classes cur_acct and sav_acct to make them more specific to their requirements. Include necessary member functions in order to achieve the following tasks:

●	Accept deposits from a customer and update the balance.
●	Display the balance.
●	Compute and deposit interest.
●	Permit withdrawal and update the balance.
●	Check for the minimum balance, impose penalty, necessary and update the balance.

'''
"Refer the experiment 7 of pp lab"


In [ ]:
'''15] 1.	Write a program that defines an abstract class called Vehicle containing an abstract method speed (). Derive from it two classes - FourWheeler and TwoWheeler. Create objects of derived classes and call the speed () method using these objects, passing to it the name of vehicle and speed of vehicle. In the speed () method print the vehicle name and the speed of vehicle to which speed () belongs.'''
from abc import ABC, abstractmethod

class Vehicle(ABC):
    @abstractmethod
    def speed(self,name,speed):
        pass

class FourWheeler(Vehicle):
    def speed(self,name1,speed1):
        print(name1, speed1)

class TwoWheeler(Vehicle):
    def speed(self, name2, speed2):
        print(name2, speed2)

car = FourWheeler()
bike = TwoWheeler()
name1 = input("Enter name of car = ")
speed1 = int(input("Enter speed of car = "))
name2 = input("Enter name of bike = ")
speed2 = int(input("Enter speed of bike = "))
car.speed(name1,speed1)
bike.speed(name2,speed2)


In [ ]:
'''16] '''
#1) A dictionary is represented by the score of batsmen across a match in one level of dictionary. Find the lowest score and highest score and also
#display the name of the player respectively.

d=dict()
n=int(input("Enter number of batsman= "))
for i in range(0,n):
    name = input("Enter name of batsman= ") 
    score = int(input("Enter score of batsman= "))
    d.update({name:score})
print(d)
maxvalue=0
for k,v in d.items():
    if v>maxvalue:
        maxvalue=v
        key=k
print("maximum score= ",key,maxvalue)
for k,v in d.items():
    if v<maxvalue:
        maxvalue=v
        key=k
print("minimum score= ",key,maxvalue)


In [ ]:
'''17] '''
#2
def poly_modify(poly1,poly2):
    diff=len(poly1)-len(poly2)
    if diff == 0:
        return (poly1,poly2)
    elif diff >0:
        max_pow2 = poly2[0][1]
        for i in range (diff):
            poly2.insert(0,(0,max_pow2 +1))
            max_pow2+=1
        return (poly1,poly2)
    elif diff<0:
        max_pow1=poly1[0][1]
        for i in range(-diff):
            poly1.insert(0,(0,max_pow1+1))
            max_pow1+=1
        return (poly1,poly2)
def add(p,q):
    p,q=poly_modify(p,q)
    poly_sum=[]
    for i in range(len(p)):
        coeff_sum=p[i][0] + q[i][0]
        poly_sum.append((coeff_sum,len(p)-1-i))
    return poly_sum
def sub(p,q):
    p,q=poly_modify(p,q)
    poly_diff = []
    for i in range(len(p)):
        coeff_diff = p[i][0] - q[i][0]
        poly_diff.append((coeff_diff,len(p)-1-i))
    return poly_diff
p=[]
q=[]
deg1=int(input("Enter the degree of polynomial 1 : "))
for exp in range(deg1,-1,-1):
    print("Enter the coefficient for x^",exp,":",sep ="",end="")
    coeff=int(input())
    p.append((coeff,exp))
print()
deg2=int(input("Enter the degre of polynomial 2: "))
for exp in range(deg2,-1,-1):
    print("Enter the coefficient for x^",exp,":",sep ="",end="")
    coeff=int(input())
    q.append((coeff,exp))
print()
print("p =",p)
print("q =",q)
print()
print("Addition of polynomial is:",add(p,q))
print("Difference of polynomial is:",sub(p,q))


In [ ]:
'''18] '''
#3
def det2x2(n00,n01,n10,n11):
    return n00*n11-n10*n01
def cramer(a,b,c,d,e,f):
    D =det2x2(a,b,c,d)
    if D == 0:
        return None
    Dx=det2x2(e,b,f,d)
    Dy=det2x2(a,e,c,f)
    X=Dx/D
    Y=Dy/D
    return (X,Y)
a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
e=int(input("Enter the value of c: "))
c=int(input("Enter the value of d: "))
d=int(input("Enter the value of e: "))
f=int(input("Enter the value of f: "))
soln = cramer(a,b,c,d,e,f)
if soln==None:
    print("No unique solution found")
else:
    x,y=soln
    print("The solution of two linear equation {0}x + {1}y = {2} & {3}x + {4}y = {5} is x={6} & y= {7}".format(a,b,c,d,e,f,x,y))


In [ ]:
'''19] '''
d=dict()
n=int(input("Enter n= "))
for i in range(0,n):
    ps = input("Enter key= ") 
    value = int(input("Enter value= "))
    d.update({ps:value})
print(d)
maxvalue=0
for k,v in d.items():
    if v>maxvalue:
        maxvalue=v
        key=k
print("Highest score= ",key,maxvalue)
for k,v in d.items():
    if v<maxvalue:
        maxvalue=v
        key=k
print("Lowest score= ",key,maxvalue)


In [ ]:
'''20] '''
#5Write a python function add(n) where n is any positive integer, function
#will return addition of the digits of n repeatedly until the result has single
#digit.
def add(n):
    if n<10:
        return n
    else:

        unit=n%10
        n=n//10
        return add(unit+add(n)) 
n=int(input("Enter the value of n= "))
sum=add(n)
print(sum)


In [ ]:
'''21] '''
#4]
r=int(input("Enter number of row= "))
c=int(input("Enter number of column= "))
mat=[]
for i in range(r):
    a=[]
    for j in range(c):
        a.append(int(input()))
    mat.append(a) 
for i in range(r):
    for j in range(c):
        print(mat[i][j],end=" ")
    print()


In [ ]:
'''22] '''
#Q7)
n=int(input("Enter number= "))
for i in range(0,n):
    for j in range(0,n):
       
        if i+j==3:
            print(0,end="")
        elif i+j==4:
            print(1,end="")
        else:
            print(i+j,end="")          
    print("")


In [ ]:
'''23] '''
#8) Write a python function right_triangle(x) which will print the following pattern.
n=int(input("Enter number of rows= "))
for i in range(0,n):
    for j in range(0,i+1):
        print(j,end="")
        j+=j
    print("")
    i+=i


In [ ]:
'''24] '''
# 9]
import re
input_name = input("Enter username= ")
input_password = input("Enter your password= ")
input_emailid = input("Enter your email id= ")
input_mobile=input('Enter your mobile number= ')
pattern1 = r'[A-Za-z]{6,10}'
pattern2 = r'^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$'
pattern3 = r'[A-Za-z0-9]+@email.com'
pattern4=r'[6-9]\d{9}'
if re.search(pattern1, input_name):
    print("valid username")
    input_name = True
else:
    print("invalid username")
if re.search(pattern2, input_password):
    print("valid password")
    input_password = True
else:
    print("invalid password")
if re.search(pattern3, input_emailid):
    print("valid email id")
    input_emailid = True
else:
    print("invalid email id")
if re.search(pattern4,input_mobile):
    print("valid mobile number")
    input_mobile=True
else:
    print('invalid mobile number')
if input_name == True:
    if input_password == True:
        if input_emailid == True:
            if input_mobile == True:
                print("Thank You!!")
            else:
                print("Sorry try again!!")
        else:
            print("Sorry try again!!")
    else:
        print("Sorry try again!!")
else:
    print("Sorry try again!!")


In [4]:
'''25] '''
#Q10)
import re
txt='''Name: Patel Umang Jayantibhai
Account number: 10101010101010
IFSC code: UNIN00897
email id: xyz@gh.com
pin code: 401101
mob no: 9870765910

Name: Shah Umang Jayantibhai
Account number: 10101010102022
IFSC code: UNIN00997
email id: pqr@gh.com
pin code: 400001
mob no: 1234567890
MICR code: UNINN8907

Name: Shah ritik
Account number: 10201010102022
IFSC code: UNIN00997
email id: pqr@gmail.com
pin code: 400001
mob no: 6789678998

email id: taha@gmail.com
pin code: 400001
mob no: 6789678998
Name: taha zubain
Account number: 10201010102022
IFSC code: UNIN00997
MICR code: UNNIN0909'''

pattern1=r'[10]\d{12}'
acc=re.findall(pattern1,txt)
print("account number list ",acc)
pattern2=r'[6-9]\d{9}'
phone=re.findall(pattern2,txt)
print("phone number list ",phone)
pattern3=r'[A-Za-z]{4}[0-9]{5}'
IFC=re.findall(pattern3,txt)
print("IFC Code list ",IFC)
pattern4 = r'Name: (\b[A-Za-z]{3,}\b \b[A-Za-z]{3,}\b(?:[A-Za-z ]{3,})?\b)'
#pattern4=r'(\b[A-Za-z]{3,}\b \b[A-Za-z]{3,}\b \b[A-Za-z]{3,}\b)'
#pattern4 = r'Name: (\b[A-Za-z]{3,}\b \b[A-Za-z]{3,}\b(?:[A-Za-z ]{3,})?\b) Account'
name=re.findall(pattern4,txt)
print("name list ",name)


account number list  ['1010101010101', '1010101010202', '1020101010202', '1020101010202']
phone number list  ['9870765910', '6789678998', '6789678998']
IFC Code list  ['UNIN00897', 'UNIN00997', 'UNIN00997', 'UNIN00997']
name list  ['Patel Umang Jayantibhai', 'Shah Umang Jayantibhai', 'Shah ritik', 'taha zubain']


In [ ]:
# 8) Write a python function right_triangle(x) which will print the following pattern.
'''n=int(input("Enter number of rows= "))
for i in range(0,n):
    for j in range(0,n):
        print((n-1)*j*i,end="")
        j+=j
    print("")
    i+=i'''
# 5Write a python function add(n) where n is any positive integer, function
# will return addition of the digits of n repeatedly until the result has single
# digit.
'''def add(n):
    if n<10:
        return n
    else:

        unit=n%10
        n=n//10
        return add(unit+add(n)) 
n=int(input("Enter the value of n= "))
sum=add(n)
print(sum)'''

# 9]
'''import re
input_name = input("Enter username= ")
input_password = input("Enter your password= ")
input_emailid = input("Enter your email id= ")
input_mobile=input('Enter your mobile number= ')
pattern1 = r'[A-Za-z]{6,10}'
pattern2 = r'^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$'
pattern3 = r'[A-Za-z0-9]+@email.com'
pattern4=r'[6-9]\d{9}'
if re.search(pattern1, input_name):
    print("valid username")
    input_name = True
else:
    print("invalid username")
if re.search(pattern2, input_password):
    print("valid password")
    input_password = True
else:
    print("invalid password")
if re.search(pattern3, input_emailid):
    print("valid email id")
    input_emailid = True
else:
    print("invalid email id")
if re.search(pattern4,input_mobile):
    print("valid mobile number")
    input_mobile=True
else:
    print('invalid mobile number')
if input_name == True:
    if input_password == True:
        if input_emailid == True:
            if input_mobile == True:
                print("Thank You!!")
            else:
                print("Sorry try again!!")
        else:
            print("Sorry try again!!")
    else:
        print("Sorry try again!!")
else:
    print("Sorry try again!!")'''

#4]Write a python function matrix(r,c) where r is no of row and c is no of
#column. The function matrix will return matrix with size of rxc with
#element 1 to rxc with an increment in a row manner.
'''r=int(input("Enter number of row= "))
c=int(input("Enter number of column= "))
mat=[]
for i in range(r):
    a=[]
    for j in range(c):
        a.append(int(input()))
    mat.append(a) 
for i in range(r):
    for j in range(c):
        print(mat[i][j] ,end=" ")
    print( )'''

#2
'''def poly_modify(poly1,poly2):
    diff=len(poly1)-len(poly2)
    if diff == 0:
        return (poly1,poly2)
    elif diff >0:
        max_pow2 = poly2[0][1]
        for i in range (diff):
            poly2.insert(0,(0,max_pow2 +1))
            max_pow2+=1
        return (poly1,poly2)
    elif diff<0:
        max_pow1=poly1[0][1]
        for i in range(-diff):
            poly1.insert(0,(0,max_pow1+1))
            max_pow1+=1
        return (poly1,poly2)
def add(p,q):
    p,q=poly_modify(p,q)
    poly_sum=[]
    for i in range(len(p)):
        coeff_sum=p[i][0] + q[i][0]
        poly_sum.append((coeff_sum,len(p)-1-i))
    return poly_sum
def sub(p,q):
    p,q=poly_modify(p,q)
    poly_diff = []
    for i in range(len(p)):
        coeff_diff = p[i][0] - q[i][0]
        poly_diff.append((coeff_diff,len(p)-1-i))
    return poly_diff
p=[]
q=[]
deg1=int(input("Enter the degree of polynomial 1 : "))
for exp in range(deg1,-1,-1):
    print("Enter the coefficient for x^",exp,":",sep ="",end="")
    coeff=int(input())
    p.append((coeff,exp))
print()
deg2=int(input("Enter the degre of polynomial 2: "))
for exp in range(deg2,-1,-1):
    print("Enter the coefficient for x^",exp,":",sep ="",end="")
    coeff=int(input())
    q.append((coeff,exp))
print()
print("p =",p)
print("q =",q)
print()
print("Addition of polynomial is:",add(p,q))
print("Difference of polynomial is:",sub(p,q))'''

#3
def det2x2(n00,n01,n10,n11):
    return n00*n11-n10*n01
def cramer(a,b,c,d,e,f):
    D =det2x2(a,b,c,d)
    if D == 0:
        return None
    Dx=det2x2(e,b,f,d)
    Dy=det2x2(a,e,c,f)
    X=Dx/D
    Y=Dy/D
    return (X,Y)
a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
e=int(input("Enter the value of c: "))
c=int(input("Enter the value of d: "))
d=int(input("Enter the value of e: "))
f=int(input("Enter the value of f: "))
soln = cramer(a,b,c,d,e,f)
if soln==None:
    print("No unique solution found")
else:
    x,y=soln
    print("The solution of two linear equation {0}x + {1}y = {2} & {3}x + {4}y = {5} is x={6} & y= {7}".format(a,b,c,d,e,f,x,y))



In [25]:
class person:
    def __init__(self):
        self.name="sam"
        
    def talk(self):
        print("hi i m ",self.name)
obj=person()
obj.talk()

hi i m  sam


In [ ]:
'''Q26]'''
from abc import ABC, abstractmethod

class Vehicle(ABC):
    @abstractmethod
    def speed(self,name,speed):
        pass

class FourWheeler(Vehicle):
    def speed(self,name1,speed1):
        print(name1, speed1)

class TwoWheeler(Vehicle):
    def speed(self, name2, speed2):
        print(name2, speed2)

car = FourWheeler()
bike = TwoWheeler()
name1 = input("Enter name of car = ")
speed1 = int(input("Enter speed of car = "))
name2 = input("Enter name of bike = ")
speed2 = int(input("Enter speed of bike = "))
car.speed(name1,speed1)
bike.speed(name2,speed2)
from abc import ABC, abstractmethod
class Employee(ABC):
    @abstractmethod
    def calculate_salary(self,sal):
        pass
    
class Developer(Employee):
    def calculate_salary(self,sal):
        finalsalary=sal*1.10
        return finalsalary
        
emp_1=Developer()
print(emp_1.calculate_salary(10000))

In [1]:
#Q27]

class Bank:
    def getroi(self):
        return 10

class SBI:
        def getroi(self):
            return 7
        
class ICICI:
   def getroi(self):
        return 8

b1=Bank()
b2=SBI()
b3=ICICI()
print("Bank rate of interest:",b1.getroi())
print("SBI rate of interest:",b2.getroi())
print("ICICI rate of interest:",b3.getroi())

Bank rate of interest: 10
SBI rate of interest: 7
ICICI rate of interest: 8


In [27]:
class student:
    def __init__(self,aname,asection,aroll):
        self.name=aname
        self.section=asection
        self.roll=aroll
harry=student("harry","A",16010121210)
lst=dict
a=harry.name,harry.section,harry.roll
lst.update(self:name)
print(lst)



SyntaxError: invalid syntax (323405688.py, line 9)

In [28]:
class person:
    def __init__(self):
        self.name="sam"
        
    def talk(self):
        print("hi i m ",self.name)
obj=person()
person.talk(obj)

hi i m  sam


In [4]:
class store:
    stname=[]
    pri=[]
    def menu():
        print("Name of product\tPrice")
        n=input()
        p=input()
        stname.append(n)
        pri.append(p)
        print(stname,pri)
print(menu())
        

NameError: name 'menu' is not defined

In [1]:
import statistics

admins={"user1":"123","user2":"456"}
studentdict={"preeti":[78,88,89],"sameer":[45,55,69],"sam":[98,89,97]}
def entergrade():
    name=input("Enter student name: ")
    grade=float(input("Grade: "))
    if name in studentdict:
        print("Adding grades")
        studentdict[name].append(grade)
    else:
        print("Student does not exist")
    print(studentdict)
def removestud():
    sname=input("Enter student name you want to delete: ")
    if sname in studentdict:
        print("Removing student")
        studentdict.pop(sname)
    else:
        print("That student does not exist")
    print(studentdict)
def avg():
    for i in studentdict:
        gradelist=studentdict[i]
        avg=statistics.mean(gradelist)
        print("Average of {} student is {}".format(i,avg))
def main():
    print('''Welcome to Grade central
    [1]-Enter Grades
    [2]-Remove student
    [3]-Student Average Grades
    [4]-Exit''')
    action=input("what would you like to do today?[Enter a number] ")
    if action=='1':
        entergrade()
    elif action=="2":
        removestud()
    elif action=="3":
        avg()
    elif action=="4":
        exit()
    else:
        print("invalid choice,Try again")


login=input("Username: ")
passw=input("Password: ")
if login in admins:
    if admins[login]==passw:
        print("Welcome,",login)
        while True:
            main()
    else:
        print("Invalid password")
else:
    print("Invalid username")

SyntaxError: cannot assign to True (3613235913.py, line 41)

# Numpy in Python

In [10]:
arr1=[[1,2,3,4,5],
     [2,3,4,5,6],
     [3,4,5,6,7]]
print(arr1)

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]


In [12]:
np.array(arr1)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
import numpy as np

In [14]:
arr1[:,1]

TypeError: list indices must be integers or slices, not tuple

In [15]:
arr1.shape

AttributeError: 'list' object has no attribute 'shape'

In [16]:
type(arr1)

list

In [17]:
np.array(arr1)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [18]:
type(arr1)

list

In [19]:
arr=np.array([[1,2,3,4,5],
     [2,3,4,5,6],
     [3,4,5,6,7]])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr[:,1]

array([2, 3, 4])

In [24]:
arr[:,0::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

# EDA

In [25]:
arr<2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [28]:
print(arr[arr<4])

[1 2 3 2 3 3]


In [29]:
arr.shape

(3, 5)

In [30]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

# Mechanism to create an array

In [74]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
np.zeros((2,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.random.randint(1,3,4).reshape(2,2)

array([[2, 1],
       [2, 2]])

In [66]:
np.random.randn(1,3)

array([[ 0.37288255, -0.31015899,  1.01296827]])

In [69]:
np.random.random_sample((1,5))

array([[0.14052851, 0.00789004, 0.24515762, 0.06220163, 0.42299227]])

# Pandas in Python

Pandas Dataframe
Pandas Series
Pandas Basic Operations

Agar hame excel file k saath ya JSON file k saath kaam karna hai toh hame usse pehle DATAFRAMES mai convert karna padega aur vo hota hai Pndas ka use karke

In [70]:
!pip install pandas

In [75]:
import pandas as pd
import numpy as np

In [80]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),
            index=["Row1",
                  "ROW2",
                  "Row3",
                  "ROW4",
                  "Row5"],
            columns=["Column1",
                   "Column2",
                   "Column3",
                   "Column4"])

Dataframe is a kind of Data Structure and to build it you have to use pandas lib.

In [81]:
type(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


info() column ka datatype deta hai

In [82]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

INDEXING

In [83]:
df[["Column1","Column2"]]

Column1  Column2
Row1        0        1
ROW2        4        5
Row3        8        9
ROW4       12       13
Row5       16       17

jab ham multiple row aur multiple columns ko combone kr dete haai toh usse ham bolte hai DATAFRAMES and agar sirf ek row hai aur ek column hai toh usse ham bolenge SERIES

USING ROW INDEX NAME USING LOC

In [84]:
df.loc['ROW2']

Column1    4
Column2    5
Column3    6
Column4    7
Name: ROW2, dtype: int32

In [85]:
type(df.loc['ROW2'])

pandas.core.series.Series

USING ILOC

In [86]:
df.iloc[2:4,:3]

Column1  Column2  Column3
Row3        8        9       10
ROW4       12       13       14

# Convert dataframes into arrays

In [88]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# BASIC OPERATIONS

In [89]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
ROW2        4        5        6        7
Row3        8        9       10       11
ROW4       12       13       14       15
Row5       16       17       18       19

In [91]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [108]:
df1=pd.DataFrame(data=[[1,2,2,4],[1,np.nan,4,np.nan]],
            index=["Row1",
                  "ROW2"],
            columns=["Column1",
                   "Column2",
                   "Column3",
                   "Column4"])

In [111]:
df1=pd.DataFrame(data=[[1,2,2,4],[1,2,4,5]],
            index=["Row1",
                  "ROW2"],
            columns=["Column1",
                   "Column2",
                   "Column3",
                   "Column4"])

In [109]:
df1

Column1  Column2  Column3  Column4
Row1        1      2.0        2      4.0
ROW2        1      NaN        4      NaN

In [112]:
df1

Column1  Column2  Column3  Column4
Row1        1        2        2        4
ROW2        1        2        4        5

In [94]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
Column4    1
dtype: int64

In [99]:
df1.isnull().sum()==True

Column1    False
Column2     True
Column3    False
Column4     True
dtype: bool

In [115]:
df1["Column1"].value_counts()

1    2
Name: Column1, dtype: int64

In [116]:
df1["Column1"].unique()

array([1], dtype=int64)